### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [LazyEmpiricist/enc_file#25]
Dear Hendrik,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by LazyEmpiricist** [comment]
Dear Aleksandr,
thanks for your suggestion. Generated an .exe and provided it using "Releases" and an additional folder.

**Comment by sergeevabc** [comment]
Oh, it’s buggy: occupies available memory, causes disk trashing, then aborts with the error as follows

``` console
$ wmic ComputerSystem get TotalPhysicalMemory
4293378048

$ stat -c %s CityLights1931.mkv
4658941558

$ enc_file hash CityLights1931.mkv  
memory allocation of 4294967296 bytes failed
```

![](https://i3.imageban.ru/out/2021/03/31/19d8f771813b636eee2541c8e0ea81c3.png)

**Comment by sergeevabc** [comment]
Already [addressed it][1], yet the upstream, who happens to be @oconnor663 does nothing so far.

[1]: https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510
